# game.py

import time
from quoridor_5x5_env import GameState5x5, get_next_states
from abpruning import alpha_beta_search

def draw_board(state: GameState5x5):
    """Renders the 5x5 board in the terminal."""
    print("\n" + "="*30)
    print(f" P1 Walls: {state.p1_walls} | P2 (AI) Walls: {state.p2_walls}")
    print("="*30)
    
    # Column headers
    print("    0   1   2   3   4")
    
    for r in range(5):
        # 1. Print the row with pawns and vertical walls
        row_str = f" {r} "
        for c in range(5):
            # Check pawns
            if (c, r) == state.p1_pos:
                row_str += " P1 "
            elif (c, r) == state.p2_pos:
                row_str += " P2 "
            else:
                row_str += "  . "
            
            # Check vertical walls to the right of this cell
            if c < 4:
                if (c, r) in state.v_walls or (c, r - 1) in state.v_walls:
                    row_str += "|"
                else:
                    row_str += " "
        print(row_str)
        
        # 2. Print the horizontal wall boundaries below this row
        if r < 4:
            wall_str = "   "
            for c in range(5):
                # Check horizontal walls below this cell
                if (c, r) in state.h_walls or (c - 1, r) in state.h_walls:
                    wall_str += "--- "
                else:
                    wall_str += "    "
                
                # Intersection '+'
                if c < 4:
                    wall_str += "+"
            print(wall_str)
    print("==============================\n")

def get_human_move(state: GameState5x5):
    """Prompts the human player for a valid move."""
    valid_states = get_next_states(state)
    
    while True:
        print("Commands:")
        print("  Move: m <col> <row>       (e.g., m 2 1)")
        print("  Wall: w <col> <row> <h/v> (e.g., w 1 1 h)")
        cmd = input("Your Move (P1) > ").strip().lower().split()
        
        if not cmd: continue
        
        try:
            # Parse human input into the same format the AI uses
            action_type = "move" if cmd[0] == 'm' else "wall"
            c, r = int(cmd[1]), int(cmd[2])
            
            target_action = None
            if action_type == "move":
                target_action = {"type": "move", "pos": (c, r)}
            elif action_type == "wall" and len(cmd) == 4:
                target_action = {"type": "wall", "pos": (c, r), "orientation": cmd[3][0]}
            
            # Check if this action matches any of the legal moves generated by the engine
            for move_dict in valid_states:
                if move_dict["action"] == target_action:
                    return move_dict["state"] # Return the new board state
            
            print(">>> ILLEGAL MOVE! Try again. (Blocked by wall, out of bounds, or traps a player)\n")
        except Exception:
            print(">>> INVALID FORMAT! Use 'm x y' or 'w x y h/v'.\n")

def main():
    # Initialize the starting 5x5 board
    # P1 starts top middle (2,0), P2 starts bottom middle (2,4)
    current_state = GameState5x5(
        p1_pos=(2, 0), p2_pos=(2, 4),
        p1_walls=3, p2_walls=3,
        h_walls=[], v_walls=[],
        turn=1 # 1 = Human, 2 = AI
    )
    
    SEARCH_DEPTH = 4 # Adjust this to make the AI smarter (but slower)
    
    print("Welcome to CLI Quoridor 5x5!")
    print("You are P1. The AI is P2. Your goal is row 4. AI's goal is row 0.")
    
    while True:
        draw_board(current_state)
        
        # Check Win Conditions
        if current_state.p1_pos[1] == 4:
            print("🎉 YOU WIN! 🎉")
            break
        elif current_state.p2_pos[1] == 0:
            print("💀 AI WINS! 💀")
            break
            
        if current_state.turn == 1:
            # Human Turn
            current_state = get_human_move(current_state)
            
        else:
            # AI Turn
            print("🤖 AI is thinking...")
            start_time = time.time()
            
            best_score, best_action = alpha_beta_search(
                state=current_state,
                depth=SEARCH_DEPTH,
                alpha=float('-inf'),
                beta=float('inf'),
                is_maximizing=True,
                ai_player_id=2
            )
            
            # Find the state that corresponds to the AI's chosen action
            for move_dict in get_next_states(current_state):
                if move_dict["action"] == best_action:
                    current_state = move_dict["state"]
                    break
                    
            elapsed = time.time() - start_time
            
            # Announce what the AI decided to do
            if best_action["type"] == "move":
                print(f"🤖 AI moved to {best_action['pos']} (Took {elapsed:.2f}s, Eval: {best_score})")
            else:
                w_dir = "Horizontal" if best_action["orientation"] == 'h' else "Vertical"
                print(f"🤖 AI placed {w_dir} wall at {best_action['pos']} (Took {elapsed:.2f}s, Eval: {best_score})")

if __name__ == "__main__":
    main()